"Booleanos"
true false

"Números"
42            "Integer"
3.14          "Float"
2/3           "Fracción (Fraction)"
1.23s2        "ScaledDecimal (1.23 con escala 2) en algunos dialectos"
16rFF         "Entero en base 16"
2r1011        "Entero en base 2"

"Caracteres y cadenas"
$a             "Character"
'Hola'         "String"

"Símbolos (identificadores inmutables)"
#hola
#with:with:    "símbolo de selector keyword"

"Puntos (pares x@y)"
3@4

"Arreglos literales (inmutables)"
#(1 2 3 'a' #ok)

"Arreglos de bytes"
#[16rFF 1 2 3]
